version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: circleci/node:erbium
    steps:
      - checkout
      - node:
          steps:
            - run: npm install -g node-gyp-cache
            - run: npm config set node_gyp node-gyp-cache
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
